### ISSUE TITLE
No script found

### ISSUE THREAD

**Issue by yichunhuang** [ifcwebserver/IFC-to-Neoj4#2]
I cannot find "IFC 2 Graph DB" script from the "scripts" dropdown list. Need more instructions, please.

**Comment by ifcwebserver** [comment]
The script has been removed from the list for moment. The IFC models can be converted into Neo4j graph database on the server on request.

Please upload the IFC model and send me a short notification at ifcwebserver@gmail.com

**Comment by yichunhuang** [comment]
> The script has been removed from the list for moment. The IFC models can be converted into Neo4j graph database on the server on request.
> 
> Please upload the IFC model and send me a short notification at [ifcwebserver@gmail.com](mailto:ifcwebserver@gmail.com)

Should I provide my ifcwebserver account ID for you in email? and which version should I upload? Thank you.
![ifc_image](https://user-images.githubusercontent.com/38839638/50723173-0d802c80-1115-11e9-8c05-71d8c9f880fa.png)

**Comment by ifcwebserver** [comment]
you can use any option according to your needs, the best is IFC2x3 coordination view 2.
There are some options to export the Revit properties also (you have to click on modify setup to see them)

send me the account id and the model name and what do you want to do with the graph database. It will hosted on the sever and you will be able to do graph queries inside the online BIM viewer, you will not be able to create the database on your local PC.
