### ISSUE TITLE
No Link 

### ISSUE THREAD

**Issue by roselins** [ifcwebserver/IFC-to-Neoj4#3]
Hi Ali, 
I'm trying to add a random IFC File to my Neo4j Database. I cant press on the (start IFC--> Neo4J) because it is not a link. it is just a text. so how could I get the Cypher commands?

I hope you can help me. 

![Unbenannt](https://user-images.githubusercontent.com/44683778/55016135-7aa5ae80-4fee-11e9-83f5-a02807c46f71.PNG)

**Comment by saikreddy** [comment]
Same problem with me!!
Hello roselins , if you find out any other method to convert IFC to Neo4j, please inform me.

**Comment by BvBerkum** [comment]
Hi Ali,

I got the same problem as above. Is there away to recieve or get the Cypher commands? 
Thanks in advanced.

**Comment by fumiyamaz** [comment]
Hi Ali,
I also got the same problem as above.
Thanks,

**Comment by BvBerkum** [comment]
Hi Ali,

Is it possible to recieve an update about this issue? 

Kind regards

**Comment by ifcwebserver** [comment]
Exporting Cypher commands is disabled since a while.
The process of converting IFC models to Neo4i it totally automated now to be hosted only on the server.
